language: php

php:
  - '5.6'
  - '7.0'

before_script:
  - echo 'date.timezone = "UTC"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

before_install:
  - sudo apt-get update -qq -y
  - sudo apt-get install -qq -y php5-gd

install:
  - composer install

after_success:
  - travis_retry php bin/coveralls -v