language: php

php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'

before_script:
  - echo 'date.timezone = "UTC"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'extension = "xdebug.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_install:
  - sudo apt-get update -qq -y
  - sudo apt-get install -qq -y php5-gd

install:
  - composer install